name: Build and Deploy Vue.JS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.11"

      - run: corepack enable
#      - run: npm i -g pnpm

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Build Vue
        run: pnpm i
        
      - run: pnpm build

      - name: Deploy to Branch
        uses: qoomon/actions--publish-to-github-pages@v1
        with:
          GITHUB_PAGES_REPLACE: true
